apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jellyfin-exporter
  labels:
    release: prometheus
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: jellyfin
  namespaceSelector:
    matchNames:
      - jellyfin
  endpoints:
    - port: metrics
      interval: 30s