# global:
#   env:
#     - name: AUTHENTIK_DEBUG
#       value: "true"

global:
  volumes:
    - name: credentials
      secret:
        secretName: authentik-secret
  volumeMounts:
    - name: credentials
      mountPath: /credentials
      readOnly: true

authentik:
  secret_key: file:///credentials/secret-key
  # This sends anonymous usage-data, stack traces on errors and
  # performance data to sentry.io, and is fully opt-in
  error_reporting:
    enabled: true
  postgresql:
    host: file:///credentials/postgresql-host
    name: file:///credentials/postgresql-name
    port: file:///credentials/postgresql-port
    user: file:///credentials/postgresql-user
    password: file:///credentials/postgresql-password
  redis:
    host: file:///credentials/redis-host
    password: file:///credentials/redis-password


server:
  name: "server"
  startupProbe:
    initialDelaySeconds: 35
  readinessProbe:
    initialDelaySeconds: 15
  volumes:
    - name: authentik-media-nfs
      persistentVolumeClaim:
        claimName: authentik-media-nfs
  volumeMounts:
    - mountPath: /media
      name: authentik-media-nfs
      subPath: "media/"
  ingress:
    enabled: false

redis:
  enabled: false