apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: immich
  namespace: immich
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`immich.umhomelab.com`) || Host(`www.immich.umhomelab.com`)
      kind: Rule
      services:
        - name: immich-server
          namespace: immich
          port: 3001
  tls: {}