---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: umhomelab-com
  namespace: default
spec:
  secretName: umhomelab-com
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.umhomelab.com"
  dnsNames:
    - "umhomelab.com"
    - "*.umhomelab.com"