apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee
  namespace: zigbee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zigbee
  template:
    metadata:
      name: zigbee
      labels:
        app: zigbee
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        sysctls:
          - name: net.ipv4.ip_unprivileged_port_start
            value: "80"
      volumes:
        - name: zigbee-nfs
          persistentVolumeClaim:
            claimName: zigbee-nfs
      containers:
        - name: zigbee
          image: docker.io/koenkk/zigbee2mqtt:2.7.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: zigbee-nfs
              mountPath: /app/data
              subPath: "config/"
          env:
            - name: TZ
              value: "Europe/Zurich"
          securityContext:
            privileged: true # Container must run as privileged inside of the pod, required for hardware acceleration
---
apiVersion: v1
kind: Service
metadata:
  name: zigbee-svc
  namespace: zigbee
spec:
  selector:
    app: zigbee
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 192.168.31.228
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: zigbee
  namespace: zigbee
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`zigbee.umhomelab.com`)
      kind: Rule
      middlewares:
        - name: authentik
          namespace: auth
      services:
        - name: zigbee-svc
          namespace: zigbee
          port: 80
  tls: {}