thickPlugin:
  enabled: true

config:
  daemon_conf:
    cniBinDir: /opt/cni/bin
    cniConfigDir: /hostroot/var/lib/rancher/k3s/agent/etc/cni/net.d
    multusAutoconfigDir: /hostroot/var/lib/rancher/k3s/agent/etc/cni/net.d
