apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: lan-network
  namespace: default
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "lan-network",
    "type": "ipvlan",
    "master": "ens18",
    "ipam": {
      "type": "static",
      "routes": [
        { "dst": "192.168.31.0/24", "gw": "192.168.31.1"}
      ]
    }
  }'
