---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
spec:
  ingressClassName: traefik-external
  entryPoints:
    - websecure
  routes:
    - match: Host(`traefik.umhomelab.com`) || Host(`www.traefik.umhomelab.com`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
  tls: {}