apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
  namespace: guaca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacamole
  strategy:
    type: Recreate
  template:
    metadata:
      name: guacamole
      labels:
        app: guacamole
        app.kubernetes.io/name: guacamole
    spec:
      securityContext:
        # fsGroup: 1000
        # runAsGroup: 1000
        # runAsNonRoot: true
        # runAsUser: 1000
        # fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: apache-guacamole
          image: docker.io/guacamole/guacamole:1.6.0
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRESQL_DATABASE
              value: guacamole
            - name: POSTGRESQL_HOSTNAME
              value: "postgres.db.svc"
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: guaca-secret
                  key: guaca-username
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: guaca-secret
                  key: guaca-password
            - name: POSTGRESQL_PORT
              value: "5432"
            - name: GUACD_HOSTNAME
              value: "localhost"
            - name: GUACD_PORT
              value: "4822"
            - name: EXTENSIONS
              value: auth-openid
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
        - name: apache-guacd
          image: docker.io/guacamole/guacd:1.6.0
          imagePullPolicy: IfNotPresent
          env:
            - name: EXTENSIONS
              value: auth-openid
          ports:
            - name: http
              containerPort: 4822
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: guacd
  namespace: guaca
spec:
  type: LoadBalancer
  selector:
    app: guacamole
  ports:
    - port: 80
      targetPort: 4822
---
apiVersion: v1
kind: Service
metadata:
  name: guacamole
  namespace: guaca
spec:
  type: ClusterIP
  selector:
    app: guacamole
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: guacamole
  namespace: guaca
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: "Host(`guaca.umhomelab.com`) || Host(`www.guaca.umhomelab.com`)"
      kind: Rule
      middlewares:
        - name: guacamole-subpath
          namespace: guaca
      services:
        - name: guacamole
          namespace: guaca
          port: 80
  tls: {}
