apiVersion: apps/v1
kind: Deployment
metadata:
  name: homarr
  namespace: rr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homarr
  template:
    metadata:
      name: homarr
      labels:
        app: homarr
    spec:
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        sysctls:
          - name: net.ipv4.ip_unprivileged_port_start
            value: "80"
      volumes:
        - name: homarr-config-nfs
          persistentVolumeClaim:
            claimName: homarr-config-nfs
      containers:
        - name: homarr
          image: ghcr.io/ajnart/homarr:0.16.0
          securityContext:
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
            privileged: false
          ports:
            - containerPort: 7575
          volumeMounts:
            - name: homarr-config-nfs
              mountPath: /app/data/configs
              subPath: "config/"
            - name: homarr-config-nfs
              mountPath: /data
              subPath: "data/"
            - name: homarr-config-nfs
              mountPath: /app/public/imgs
              subPath: "imgs/"
            - name: homarr-config-nfs
              mountPath: /app/public/icons
              subPath: "icons/"
          env:
            - name: AUTH_PROVIDER
              value: oidc
            - name: BASE_URL
              value: umhomelab.com
            - name: AUTH_OIDC_URI
              valueFrom:
                secretKeyRef:
                  name: homarr-secret
                  key: oidc-uri
            - name: AUTH_OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: homarr-secret
                  key: oidc-client-id
            - name: AUTH_OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: homarr-secret
                  key: oidc-client-secret
            - name: AUTH_OIDC_CLIENT_NAME
              value: "Authentik"
            - name: NEXTAUTH_URL
              value: https://umhomelab.com
            - name: DEFAULT_COLOR_SCHEME
              value: dark
            - name: AUTH_LOGOUT_REDIRECT_URL
              value: https://umhomelab.com
            - name: AUTH_SESSION_EXPIRY_TIME
              value: "30d"
            - name: AUTH_OIDC_TIMEOUT
              value: "3500"
            - name: AUTH_OIDC_ADMIN_GROUP
              valueFrom:
                secretKeyRef:
                  name: homarr-secret
                  key: oidc-admin-group
            - name: AUTH_OIDC_OWNER_GROUP
              valueFrom:
                secretKeyRef:
                  name: homarr-secret
                  key: oidc-owner-group
            - name: AUTH_OIDC_AUTO_LOGIN
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: homarr-svc
  namespace: rr
spec:
  selector:
    app: homarr
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 7575
  type: LoadBalancer
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homarr
  namespace: rr
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`www.umhomelab.com`)
      kind: Rule
      services:
        - name: homarr-svc
          port: 80
    - match: Host(`umhomelab.com`)
      kind: Rule
      services:
        - name: homarr-svc
          port: 80
  tls: {}