apiVersion: apps/v1
kind: Deployment
metadata:
  name: seerr
  namespace: rr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seerr
  template:
    metadata:
      name: seerr
      labels:
        app: seerr
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      volumes:
        - name: seerr-config-nfs
          persistentVolumeClaim:
            claimName: seerr-config-nfs
        - name: rr-media-nfs
          persistentVolumeClaim:
            claimName: rr-media-nfs
      containers:
        - name: seerr
          image: ghcr.io/seerr-team/seerr:v3.5.0
          ports:
            - containerPort: 5055
          volumeMounts:
            - name: seerr-config-nfs
              mountPath: /app/config
              subPath: "config/"
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Zurich
---
apiVersion: v1
kind: Service
metadata:
  name: seerr-svc
  namespace: rr
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.31.243
spec:
  selector:
    app: seerr
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5055
  type: LoadBalancer
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: seerr
  namespace: rr
spec:
  ingressClassName: traefik-external
  entryPoints:
    - websecure
  routes:
    - match: Host(`seerr.umhomelab.com`) || Host(`www.seerr.umhomelab.com`)
      kind: Rule
      services:
        - name: seerr-svc
          namespace: rr
          port: 80
  tls: {}