apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ratelimit
spec:
  rateLimit:
    sourceCriterion:
      ipStrategy:
        excludedIPs:
          - 127.0.0.1/32
          - 192.168.31.0/24
          - 10.0.0.0/8
    average: 100
    burst: 200
