apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      name: homepage
      labels:
        app: homepage
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        sysctls:
          - name: net.ipv4.ip_unprivileged_port_start
            value: "80"
      volumes:
        - name: homepage-nfs
          persistentVolumeClaim:
            claimName: homepage-nfs
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:v0.9.10
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: homepage-nfs
              mountPath: /app/config
              subPath: "config/"
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
---
apiVersion: v1
kind: Service
metadata:
  name: homepage-svc
  namespace: homepage
spec:
  selector:
    app: homepage
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  namespace: homepage
spec:
  rules:
    - host: h.umhomelab.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: homepage-svc
              port:
                number: 80