apiVersion: v1
kind: PersistentVolume
metadata:
  name: appsmith-nfs
  labels:
    app: appsmith
spec:
  capacity:
    storage: 1070Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.2
    - rsize=8192
    - wsize=8192
  nfs:
    server: 192.168.31.99
    path: "/mnt/ssd120/apps/appsmith"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appsmith-nfs
  namespace: appsmith
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      # minimum capacity
      storage: 100Mi
  selector:
    matchLabels:
      app: appsmith