apiVersion: v1
kind: PersistentVolume
metadata:
  name: kopia-app-nfs
spec:
  capacity:
    storage: 1070Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.2
    - rsize=8192
    - wsize=8192
  nfs:
    server: 192.168.31.99
    path: "/mnt/ssd120/apps/kopia"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kopia-app-nfs
  namespace: backup
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      # minimum capacity
      storage: 100Mi
