apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: base-app-pvc-nfs
  namespace: base
spec:
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti
  accessModes:
    - ReadWriteMany
  volumeName: base-app-pv
