apiVersion: v1
kind: Namespace
metadata:
  name: auth-od
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: authelia-nfs
  namespace: auth
spec:
  capacity:
    storage: 1070Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: 192.168.31.99
    path: "/mnt/ssd120/apps/authelia"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-nfs
  namespace: auth
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      # minimum capacity
      storage: 100Mi