kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres14-pv
  namespace: db
  labels:
    type: local
    app: postgres14
spec:
  storageClassName: nfs
  capacity:
    storage: 1070Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.2
    - rsize=8192
    - wsize=8192
  nfs:
    server: 192.168.31.99
    path: "/mnt/ssd120/apps/pg14"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres14-pvc
  namespace: db
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      # minimum capacity
      storage: 5Gi
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgres14-disruption-budget
spec:
  maxUnavailable: 1  # Ensures at most one Pod is unavailable at any time
  selector:
    matchLabels:
      app: postgres14
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres14
  namespace: db
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0 # All pods get updated
  selector:
   matchLabels:
    app: postgres14
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres14
    spec:
      terminationGracePeriodSeconds: 120
      securityContext:
        fsGroup: 999
        runAsGroup: 999
        runAsNonRoot: true
        runAsUser: 999
        fsGroupChangePolicy: "OnRootMismatch"
      volumes:
        - name: postgres-config-file
          configMap:
            name: postgre-conf
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres14-pvc
      containers:
        - name: postgres14
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh -c pg_ctl stop -D /var/lib/postgresql/data -w -m fast"]
          securityContext:
            runAsGroup: 999
            runAsNonRoot: true
            runAsUser: 999
            privileged: false
          image: postgres:17.0
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
            - mountPath: /etc/postgresql/postgresql.conf
              name: postgres-config-file
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-root-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-root-password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: postgres-dbname
---
apiVersion: v1
kind: Service
metadata:
  name: postgres14
  namespace: db
  labels:
    app: postgres14
spec:
    ports:
    - name: postgres14
      port: 5432
      nodePort: 30431
    type: NodePort
    selector:
      app: postgres14
---
apiVersion: v1
kind: Service
metadata:
  name: pg14
  namespace: db
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.31.222
spec:
  selector:
    app: postgres14
  ports:
    - port: 5432
      targetPort: 5432
  type: LoadBalancer