
apiVersion: v1
kind: Namespace
metadata:
  name: tests
apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-test
  namespace: tests
spec:
  selector:
    matchLabels:
      app: init-test
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: init-test
    spec:
      nodeName: node1
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      initContainers:
        - name: init
          image: docker.io/ubuntu:jammy
          command: ['/bin/bash', '-c']
          args:
            - |-
              touch aFile
          securityContext:
            runAsUser: 0
      containers:
        - name: init-test
          image: docker.io/ubuntu:jammy
          command: ["/bin/sh", "-c"]
          args:
            - |-
              sleep 360m
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            privileged: false