apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-router-role
  namespace: kube-system
rules:
- apiGroups: ["discovery.k8s.io/v1"]
  resources: ["endpointslices"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-router-rolebinding
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: kube-router
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: kube-router-role
  apiGroup: rbac.authorization.k8s.io