apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-app-nfs
  labels:
    app: prometheus
spec:
  capacity:
    storage: 1070Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.2
    - rsize=8192
    - wsize=8192
  nfs:
    server: 192.168.31.99
    path: "/mnt/ssd120/apps/prometheus"
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: prometheus-app-nfs
#   namespace: monitoring
# spec:
#   accessModes:
#     - ReadWriteMany
#   storageClassName: nfs
#   resources:
#     requests:
#       # minimum capacity
#       storage: 100Mi
#   selector:
#     matchLabels:
#       app: prometheus